Add unix socket
nkval/nkv pull request #36
Opened 2024-12-23 13:05 UTC by uncleDecart

2024-12-24 09:04 UTC, deitch requested changes
Just some minor typos and questions about the doc changes.

2024-12-24 09:05 UTC, deitch commented
> So making universal trait turned out to be way harder than it looks, so instead I've just switched to unix socket instead of TCP. Whoever wants to use TCP, can implement their own server and notifiers, not sure if abstracting over writer right now is a right way to go

Ah that is a pity. It would have been nice. In the meantime, yes, can be just unix domain socket.

2024-12-24 09:05 UTC, deitch commented
Also CI is failing

2024-12-24 09:13 UTC, uncleDecart commented on docs/KEYSPACE.md
> +
yes, it was the behaviour before, I just documented this explicitly, because I tried to do subscribe ks1.* and now I'm thinking that there's a difference subscribe ks1 == subscribe to changes of ks1 value, subscribe ks1.* == subscribe to changes of children of ks1, not the ks1(? not sure about this one)

2024-12-24 09:14 UTC, uncleDecart commented
>Also CI is failing

It failed to checkout branch... huh

2024-12-24 09:32 UTC, deitch commented on docs/KEYSPACE.md
> +
To some degree, it is a question of expectations. When someone does `subscribe ks1`, do they mean, "all of the individual children of ks1" or "all of the multi-generational descendants of ks1"? I think you may want to support both, where `subscribe ks1` = "ks1 itself and any multi-generational descendants, the entire ks1 keyspace", and `subscribe `ks1.*` = "the immediate children of ks1, but nothing below that", but that can be a future PR. For now, just document what the current behaviour is, so it is accurate.

It really doesn't belong in this PR, probably just a single change doc PR.

2024-12-24 09:34 UTC, deitch commented
> It failed to checkout branch... huh

Doesn't surprise me. You are doing a PR from `uncleDecart:add-unix-socket` to `nkv:main`. Your [workflow file](https://github.com/nkval/nkv/actions/runs/12467286717/workflow?pr=36) just tries to [check out the named branch](https://github.com/nkval/nkv/actions/runs/12467286717/workflow?pr=36#L50), e.g. `add-unix-socket`, from the checked out main repo, i.e. `nkval`.

2024-12-24 10:40 UTC, uncleDecart commented on docs/KEYSPACE.md
> +
> It really doesn't belong in this PR, probably just a single change doc PR.

That's what this was about, just a separate commit in a PR, will move it

2024-12-24 10:43 UTC, uncleDecart commented on README.md
> +docker run --rm -it -v /var/run/shared:/tmp/nkv/ nkv ./nkv-client
Darn it, lost the comment. I checked this with one client and one server and I figured we need to create multiple sockets, since unix one can't do multiple clients (totally forgot about it), but this in a nutshell works. We connect two containers, which are using unix sockets via a shared folder on a host side.

2024-12-27 10:05 UTC, uncleDecart commented on README.md
> +docker run --rm -it -v /var/run/shared:/tmp/nkv/ nkv ./nkv-client
Tested with two clients with docker and locally, works as it is

2024-12-27 11:04 UTC, uncleDecart commented
@deitch fixed CI, works now, will open PR with docs and tests for keyspace once this one is merged. Next step is to figure out EVE integration and protocol schema

2024-12-30 11:40 UTC, merged